export const CHANGE_FORM = 'CHANGE_FORM'
export const SET_AUTH = 'SET_AUTH'
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const LOGOUT = 'LOGOUT'
export const REQUEST_ERROR = 'REQUEST_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// FETCH TRIPS
export const FETCH_TRIPS = 'FETCH_TRIPS'
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS'
export const FETCH_TRIPS_ERROR = 'FETCH_TRIPS_ERROR'
export const RESET_TRIPS = 'RESET_TRIPS'
export const TRIPS_FILTER = 'TRIPS_FILTER'

// NEW TRIP
export const NEW_TRIP_CHANGE_FORM = 'NEW_TRIP_CHANGE_FORM'
export const NEW_TRIP = 'NEW_TRIP'
export const NEW_TRIP_SUCCESS = 'NEW_TRIP_SUCCESS'
export const NEW_TRIP_ERROR = 'NEW_TRIP_ERROR'
export const RESET_NEW_TRIP = 'RESET_NEW_TRIP'

// FETCH TRIP
export const FETCH_TRIP = 'FETCH_TRIP' 
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS'  
export const FETCH_TRIP_ERROR = 'FETCH_TRIP_ERROR' 
export const RESET_ACTIVE_TRIP = 'RESET_ACTIVE_TRIP'

// DELETE TRIP
export const DELETE_TRIP = 'DELETE_TRIP'
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS'
export const DELETE_TRIP_REQUEST_SENDING = 'DELETE_TRIP_REQUEST_SENDING'

// EDIT TRIP
export const EDIT_TRIP_CHANGE_FORM = 'EDIT_TRIP_CHANGE_FORM'
export const EDIT_TRIP = 'EDIT_TRIP'
export const EDIT_TRIP_SUCCESS = 'EDIT_TRIP_SUCCESS'
export const EDIT_TRIP_ERROR = 'EDIT_TRIP_ERROR'
export const RESET_EDIT_TRIP = 'RESET_EDIT_TRIP'
export const EDIT_TRIP_FETCH = 'EDIT_TRIP_FETCH'
export const EDIT_TRIP_FETCH_SUCCESS = 'EDIT_TRIP_FETCH_SUCCESS'
export const EDIT_TRIP_FETCH_ERROR = 'EDIT_TRIP_FETCH_ERROR'